CREATE TABLE IF NOT EXISTS users (
    -- Primmary Keys
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    
    -- Info
    username VARCHAR(30) NOT NULL,
    

    -- Timestamp
    created_at TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
)