package repositories

import "github.com/dienggo/diego/app/models"

// UserMock is Auto generated by : diego make mock-repo user
type UserMock struct {
	UpsertResult func() error
	DeleteResult func() error
	FindResult   func() (err error, user models.User)
	GetResult    func() (err error, users []models.User)
}

func (m UserMock) Upsert(user *models.User) error {
	return m.UpsertResult()
}

func (m UserMock) Delete(id uint) error {
	return m.DeleteResult()
}

func (m UserMock) Find(id uint) (err error, user models.User) {
	return m.FindResult()
}

func (m UserMock) Get(limit int, page int) (err error, users []models.User) {
	return m.GetResult()
}
